name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'  # roda todo dia à meia-noite
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate pacman contribution graph
        uses: Platane/snk@v3
        with:
          github_user_name: macieldearaujo
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "generate pacman contribution graph" || echo "No changes to commit"
          git push
